ALTER TABLE SOCIAL_MEDIA ADD COLUMN email VARCHAR(100);
ALTER TABLE SOCIAL_MEDIA MODIFY COLUMN location VARCHAR(50);
SELECT * FROM SOCIAL_MEDIA WHERE followers_count > 50000 AND LOCATION IN ("DELHI", "MUMBAI");
